<a href="https://colab.research.google.com/github/Abhi-213/Mini-Project/blob/main/Mini_Project_Final_Version_71772118101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.6.17)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.6)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.10)

In [ ]:
!mkdir -p ~/.kaggle

In [ ]:
!mv kaggle.json ~/.kaggle/

mv: cannot stat 'kaggle.json': No such file or directory

In [ ]:
!kaggle datasets download -d vigneshvenkateswaran/bot-iot

Dataset URL: https://www.kaggle.com/datasets/vigneshvenkateswaran/bot-iot
License(s): unknown
Downloading bot-iot.zip to /content
100% 1.17G/1.17G [00:10<00:00, 154MB/s]
100% 1.17G/1.17G [00:10<00:00, 117MB/s]

In [ ]:
!unzip /content/bot-iot.zip

Archive:  /content/bot-iot.zip
  inflating: data_1.csv
  inflating: data_10.csv
  inflating: data_11.csv
  inflating: data_12.csv
  inflating: data_13.csv
  inflating: data_14.csv
  inflating: data_15.csv
  inflating: data_16.csv
  inflating: data_17.csv
  inflating: data_18.csv
  inflating: data_19.csv
  inflating: data_2.csv
  inflating: data_20.csv
  inflating: data_21.csv
  inflating: data_22.csv
  inflating: data_23.csv
  inflating: data_24.csv
  inflating: data_25.csv
  inflating: data_26.csv
  inflating: data_27.csv
  inflating: data_28.csv
  inflating: data_29.csv
  inflating: data_3.csv
  inflating: data_30.csv
  inflating: data_31.csv
  inflating: data_32.csv
  inflating: data_33.csv

In [1]:
import pandas as pd

df = pd.read_csv("/content/keylogging_formatted_trail.csv")
df.head(10)

<ipython-input-1-bca9e9598a88>:3: DtypeWarning: Columns (4,5,7,11,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/keylogging_formatted_trail.csv")

,stime,flgs,proto,saddr,sport,dir,daddr,dport,pkts,bytes,...,Unnamed: 16373,Unnamed: 16374,Unnamed: 16375,Unnamed: 16376,Unnamed: 16377,Unnamed: 16378,Unnamed: 16379,Unnamed: 16380,Unnamed: 16381,Unnamed: 16382
0,1529380744,e,tcp,192.168.100.3,54766.0,->,192.168.100.149,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1529380745,e,tcp,192.168.100.3,42954.0,->,192.168.100.150,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1529380746,e,tcp,192.168.100.3,54768.0,->,192.168.100.149,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1529380747,e,tcp,192.168.100.3,42956.0,->,192.168.100.150,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1529380748,e,tcp,192.168.100.3,54770.0,->,192.168.100.149,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1529380749,e,tcp,192.168.100.3,42958.0,->,192.168.100.150,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1529380750,e,arp,192.168.100.3,NaN,who,192.168.100.150,NaN,6,360,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1529380750,e,tcp,192.168.100.3,54772.0,->,192.168.100.149,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1529380751,e,tcp,192.168.100.3,42960.0,->,192.168.100.150,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1529380752,e,tcp,192.168.100.3,54774.0,->,192.168.100.149,4433.0,2,134,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df = df.dropna(axis=1, how='all')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4431 entries, 0 to 4430
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stime        4431 non-null   int64
 1   flgs         4431 non-null   object
 2   proto        4431 non-null   object
 3   saddr        4431 non-null   object
 4   sport        4309 non-null   object
 5   dir          1633 non-null   object
 6   daddr        4431 non-null   object
 7   dport        4309 non-null   object
 8   pkts         4431 non-null   int64
 9   bytes        4431 non-null   int64
 10  state        4431 non-null   object
 11  srcid        1633 non-null   object
 12  ltime        4431 non-null   int64
 13  seq          4431 non-null   int64
 14  dur          4431 non-null   float64
 15  mean         4431 non-null   float64
 16  stddev       4431 non-null   float64
 17  sum          4431 non-null   float64
 18  min          4431 non-null   float64
 19  max          4431 non-null   float64
 20  spkts        4431 non-null   int64
 21  dpkts        4431 non-null   int64
 22  sbytes       4431 non-null   int64
 23  dbytes       4431 non-null   int64
 24  rate         4431 non-null   float64
 25  srate        4431 non-null   float64
 26  drate        4431 non-null   float64
 27  record       1633 non-null   object
 28  attack       4431 non-null   int64
 29  category     4431 non-null   object
 30  subcategory  4431 non-null   object
dtypes: float64(9), int64(10), object(12)
memory usage: 1.0+ MB

In [4]:
df = df.drop(columns=['dir','record','srcid'])

In [5]:
from sklearn.preprocessing import LabelEncoder

for col in ['flgs', 'proto', 'saddr', 'daddr', 'state', 'category', 'subcategory']:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])

In [6]:
X = df.drop(columns=['attack'])
y = df['attack']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4431 entries, 0 to 4430
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   stime        4431 non-null   int64
 1   flgs         4431 non-null   int64
 2   proto        4431 non-null   int64
 3   saddr        4431 non-null   int64
 4   sport        4309 non-null   object
 5   daddr        4431 non-null   int64
 6   dport        4309 non-null   object
 7   pkts         4431 non-null   int64
 8   bytes        4431 non-null   int64
 9   state        4431 non-null   int64
 10  ltime        4431 non-null   int64
 11  seq          4431 non-null   int64
 12  dur          4431 non-null   float64
 13  mean         4431 non-null   float64
 14  stddev       4431 non-null   float64
 15  sum          4431 non-null   float64
 16  min          4431 non-null   float64
 17  max          4431 non-null   float64
 18  spkts        4431 non-null   int64
 19  dpkts        4431 non-null   int64
 20  sbytes       4431 non-null   int64
 21  dbytes       4431 non-null   int64
 22  rate         4431 non-null   float64
 23  srate        4431 non-null   float64
 24  drate        4431 non-null   float64
 25  attack       4431 non-null   int64
 26  category     4431 non-null   int64
 27  subcategory  4431 non-null   int64
dtypes: float64(9), int64(17), object(2)
memory usage: 969.4+ KB

In [8]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
import pandas as pd

# Handle `sport` and `dport` (hexadecimal or numeric strings)
X['sport'] = pd.to_numeric(X['sport'], errors='coerce').fillna(0).astype(int)
X['dport'] = pd.to_numeric(X['dport'], errors='coerce').fillna(0).astype(int)


# Verify all columns are numeric
print(X.dtypes)

stime            int64
flgs             int64
proto            int64
saddr            int64
sport            int64
daddr            int64
dport            int64
pkts             int64
bytes            int64
state            int64
ltime            int64
seq              int64
dur            float64
mean           float64
stddev         float64
sum            float64
min            float64
max            float64
spkts            int64
dpkts            int64
sbytes           int64
dbytes           int64
rate           float64
srate          float64
drate          float64
category         int64
subcategory      int64
dtype: object

In [9]:
y.value_counts()

attack
0    2962
1    1469
Name: count, dtype: int64

In [ ]:


# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
print(X.dtypes)

stime            int64
flgs             int64
proto            int64
saddr            int64
sport            int64
daddr            int64
dport            int64
pkts             int64
bytes            int64
state            int64
ltime            int64
seq              int64
dur            float64
mean           float64
stddev         float64
sum            float64
min            float64
max            float64
spkts            int64
dpkts            int64
sbytes           int64
dbytes           int64
rate           float64
srate          float64
drate          float64
category         int64
subcategory      int64
dtype: object

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Assuming your dataset is now in the form of DataFrames X_train and X_test

# Convert DataFrame to NumPy arrays and reshape for CNN
X_train_reshaped = X_train.values.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test_reshaped = X_test.values.reshape(X_test.shape[0], X_test.shape[1], 1)

# Define the CNN model
cnn_model = Sequential([
    Conv1D(32, kernel_size=3, activation='relu', input_shape=(X_train_reshaped.shape[1], 1)),
    MaxPooling1D(pool_size=2),
    Conv1D(64, kernel_size=3, activation='relu'),
    MaxPooling1D(pool_size=2),
    Flatten(),
    Dense(128, activation='relu'),  # Optional for regularization
    Dense(2, activation='softmax')  # Binary classification
])

# Compile the model
cnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
cnn_history = cnn_model.fit(X_train_reshaped, y_train, epochs=8, batch_size=1, validation_data=(X_test_reshaped, y_test))

Epoch 1/8
3544/3544 [==============================] - 9s 2ms/step - loss: 2077076.1250 - accuracy: 0.6851 - val_loss: 13.2057 - val_accuracy: 0.8805
Epoch 2/8
3544/3544 [==============================] - 8s 2ms/step - loss: 17285.3242 - accuracy: 0.8984 - val_loss: 255830.2344 - val_accuracy: 0.3980
Epoch 3/8
3544/3544 [==============================] - 8s 2ms/step - loss: 5338.0869 - accuracy: 0.9139 - val_loss: 13.9124 - val_accuracy: 0.9053
Epoch 4/8
3544/3544 [==============================] - 8s 2ms/step - loss: 1017.9805 - accuracy: 0.9187 - val_loss: 2655.8064 - val_accuracy: 0.8286
Epoch 5/8
3544/3544 [==============================] - 8s 2ms/step - loss: 139.2295 - accuracy: 0.8713 - val_loss: 0.3103 - val_accuracy: 0.9853
Epoch 6/8
3544/3544 [==============================] - 8s 2ms/step - loss: 10.4260 - accuracy: 0.8530 - val_loss: 0.3850 - val_accuracy: 0.7024
Epoch 7/8
3544/3544 [==============================] - 8s 2ms/step - loss: 91.1252 - accuracy: 0.8885 - val_loss: 0.2957 - val_accuracy: 0.8760
Epoch 8/8
3544/3544 [==============================] - 8s 2ms/step - loss: 48.0428 - accuracy: 0.8956 - val_loss: 1.1616 - val_accuracy: 0.8095

In [12]:
# Evaluate the CNN model on the test set
test_loss, test_accuracy = cnn_model.evaluate(X_test_reshaped, y_test)

# Print the accuracy
print(f'Test Accuracy: {test_accuracy * 100:.2f}%')

28/28 [==============================] - 0s 2ms/step - loss: 1.1616 - accuracy: 0.8095
Test Accuracy: 80.95%

In [ ]:
X_train

,stime,flgs,proto,saddr,sport,daddr,dport,pkts,bytes,state,...,max,spkts,dpkts,sbytes,dbytes,rate,srate,drate,category,subcategory
1345,1529381632,0,5,9,55642,12,4433,2,134,4,...,0.000113,1,1,74,60,8849.557617,0.000000,0.000000,1,0
3130,1528081458,0,6,11,3456,19,80,9503,9244216,0,...,4.999425,4752,4751,4514416,4729800,157.836395,78.918198,78.901581,0,1
4062,1528086368,0,5,12,0,16,0,1695,1207836,0,...,4.983598,1695,0,1207836,0,42.377499,42.377499,0.000000,0,1
52,1529380790,0,5,7,35034,16,22,31,5472,1,...,3.436743,14,17,1802,3670,8.729195,3.782651,4.655571,1,0
402,1529381035,0,5,9,54986,12,4433,2,134,4,...,0.000147,1,1,74,60,6802.721191,0.000000,0.000000,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,1528095956,0,6,11,80,19,80,357,346007,2,...,4.996722,357,0,346007,0,14.290481,14.290481,0.000000,0,1
466,1529381088,0,6,14,60300,9,53,2,258,0,...,0.031296,1,1,76,182,31.952965,0.000000,0.000000,0,1
3092,1528081343,0,6,9,26665,31,53,2,1209,0,...,0.057519,1,1,70,1139,17.385559,0.000000,0.000000,0,1
3772,1528085377,0,6,15,365,16,565,1034,62040,2,...,4.983942,1034,0,62040,0,42.886295,42.886295,0.000000,0,1
860,1529381300,0,5,9,43451,13,4433,2,134,4,...,0.000116,1,1,74,60,8620.689453,0.000000,0.000000,1,0

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Dropout
from tensorflow.keras.regularizers import l2
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Assuming you already have the dataset loaded in X_train and y_train

# Convert DataFrame to NumPy arrays and reshape for RNN (input_shape is (timesteps, features))
X_train_reshaped = X_train.values.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test_reshaped = X_test.values.reshape(X_test.shape[0], X_test.shape[1], 1)

# Define a more complex RNN model
rnn_model = Sequential([
    SimpleRNN(64, activation='tanh', return_sequences=True, input_shape=(X_train_reshaped.shape[1], 1)),
    Dropout(0.9), # Higher dropout for regularization
    SimpleRNN(32, activation='tanh', return_sequences=True),
    Dropout(0.7),
    SimpleRNN(8, activation='tanh'),
    Dropout(0.7),
    Dense(32, activation='relu', kernel_regularizer=l2(0.01)),  # Adding L2 regularization to Dense layer
    Dense(8, activation='relu', kernel_regularizer=l2(0.01)),
    Dense(2, activation='softmax')  # Binary classification (normal vs malicious)
])

# Compile the model
rnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
rnn_history = rnn_model.fit(X_train_reshaped, y_train, epochs=8, batch_size=8, validation_data=(X_test_reshaped, y_test))

# Evaluate the model on the test data
test_loss, test_accuracy = rnn_model.evaluate(X_test_reshaped, y_test)
print(f'RNN Test Accuracy: {test_accuracy * 100:.2f}%')

# Making predictions
y_pred = rnn_model.predict(X_test_reshaped)
y_pred_classes = y_pred.argmax(axis=1)  # Convert to class labels

# Classification report
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_classes))
print(classification_report(y_test, y_pred_classes))

Epoch 1/8
443/443 [==============================] - 8s 13ms/step - loss: 0.8308 - accuracy: 0.6690 - val_loss: 0.7886 - val_accuracy: 0.6415
Epoch 2/8
443/443 [==============================] - 5s 11ms/step - loss: 0.7319 - accuracy: 0.6752 - val_loss: 0.6683 - val_accuracy: 0.6415
Epoch 3/8
443/443 [==============================] - 5s 12ms/step - loss: 0.6267 - accuracy: 0.6896 - val_loss: 0.4956 - val_accuracy: 0.7745
Epoch 4/8
443/443 [==============================] - 6s 13ms/step - loss: 0.5181 - accuracy: 0.7559 - val_loss: 0.4572 - val_accuracy: 0.7847
Epoch 5/8
443/443 [==============================] - 5s 12ms/step - loss: 0.4746 - accuracy: 0.7757 - val_loss: 0.4362 - val_accuracy: 0.7824
Epoch 6/8
443/443 [==============================] - 5s 12ms/step - loss: 0.4544 - accuracy: 0.7745 - val_loss: 0.4095 - val_accuracy: 0.7959
Epoch 7/8
443/443 [==============================] - 5s 11ms/step - loss: 0.4419 - accuracy: 0.7853 - val_loss: 0.3871 - val_accuracy: 0.8129
Epoch 8/8
443/443 [==============================] - 5s 12ms/step - loss: 0.4191 - accuracy: 0.8050 - val_loss: 0.3367 - val_accuracy: 0.8275
28/28 [==============================] - 0s 5ms/step - loss: 0.3367 - accuracy: 0.8275
RNN Test Accuracy: 82.75%
28/28 [==============================] - 0s 5ms/step
[[420 149]
 [  4 314]]
              precision    recall  f1-score   support

           0       0.99      0.74      0.85       569
           1       0.68      0.99      0.80       318

    accuracy                           0.83       887
   macro avg       0.83      0.86      0.83       887
weighted avg       0.88      0.83      0.83       887

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.regularizers import l2
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Assuming X_train, X_test, y_train, y_test are already loaded

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Reshape the data for LSTM (samples, timesteps, features)
X_train_reshaped = X_train_scaled.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test_reshaped = X_test_scaled.reshape(X_test.shape[0], X_test.shape[1], 1)

# Define the LSTM model
lstm_model = Sequential([
    LSTM(32, activation='tanh', return_sequences=True, input_shape=(X_train_reshaped.shape[1], 1)),
    Dropout(0.9),  # Increased dropout to force the model to ignore more information
    LSTM(8, activation='tanh', return_sequences=True),
    Dropout(0.8),
    LSTM(4, activation='tanh'),
    Dropout(0.8),
    Dense(32, activation='relu', kernel_regularizer=l2(0.1)),  # Stronger L2 regularization
    Dense(8, activation='relu', kernel_regularizer=l2(0.1)),
    Dense(2, activation='softmax')  # Binary classification
])

# Compile the model
lstm_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Early stopping for preventing overfitting
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train the model
lstm_history = lstm_model.fit(X_train_reshaped, y_train, epochs=8, batch_size=32,
                              validation_data=(X_test_reshaped, y_test), callbacks=[early_stopping])

# Evaluate the model on the test data
test_loss, test_accuracy = lstm_model.evaluate(X_test_reshaped, y_test)
print(f'LSTM Test Accuracy: {test_accuracy * 100:.2f}%')

# Make predictions
y_pred = lstm_model.predict(X_test_reshaped)
y_pred_classes = np.argmax(y_pred, axis=1)  # Convert probabilities to class labels

# Classification report and confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_classes))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_classes))

Epoch 1/8
111/111 [==============================] - 9s 36ms/step - loss: 1.9710 - accuracy: 0.6662 - val_loss: 1.4491 - val_accuracy: 0.6415
Epoch 2/8
111/111 [==============================] - 3s 24ms/step - loss: 1.1314 - accuracy: 0.6775 - val_loss: 0.8638 - val_accuracy: 0.6415
Epoch 3/8
111/111 [==============================] - 3s 27ms/step - loss: 0.7560 - accuracy: 0.7435 - val_loss: 0.5826 - val_accuracy: 0.8850
Epoch 4/8
111/111 [==============================] - 3s 25ms/step - loss: 0.5657 - accuracy: 0.8050 - val_loss: 0.3723 - val_accuracy: 0.9605
Epoch 5/8
111/111 [==============================] - 3s 25ms/step - loss: 0.4765 - accuracy: 0.8324 - val_loss: 0.2950 - val_accuracy: 0.9639
Epoch 6/8
111/111 [==============================] - 3s 25ms/step - loss: 0.4715 - accuracy: 0.8251 - val_loss: 0.2828 - val_accuracy: 0.9673
Epoch 7/8
111/111 [==============================] - 3s 24ms/step - loss: 0.4266 - accuracy: 0.8499 - val_loss: 0.2555 - val_accuracy: 0.9696
Epoch 8/8
111/111 [==============================] - 3s 23ms/step - loss: 0.4188 - accuracy: 0.8428 - val_loss: 0.2409 - val_accuracy: 0.9696
28/28 [==============================] - 0s 6ms/step - loss: 0.2409 - accuracy: 0.9696
LSTM Test Accuracy: 96.96%
28/28 [==============================] - 1s 7ms/step
Confusion Matrix:
[[545  24]
 [  3 315]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       569
           1       0.93      0.99      0.96       318

    accuracy                           0.97       887
   macro avg       0.96      0.97      0.97       887
weighted avg       0.97      0.97      0.97       887

In [18]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from scipy.stats import mode

# Assuming cnn_model, rnn_model, lstm_model are already trained

# Make predictions for the test data
cnn_predictions = cnn_model.predict(X_test_reshaped)
rnn_predictions = rnn_model.predict(X_test_reshaped)
lstm_predictions = lstm_model.predict(X_test_reshaped)

# Convert predictions from probabilities to class labels
cnn_classes = np.argmax(cnn_predictions, axis=1)
rnn_classes = np.argmax(rnn_predictions, axis=1)
lstm_classes = np.argmax(lstm_predictions, axis=1)

# Stack the predictions to create a (samples, models) array
all_predictions = np.vstack((cnn_classes, rnn_classes, lstm_classes)).T

# Perform Majority Voting (for each sample, take the mode of the predictions)
majority_vote_predictions = mode(all_predictions, axis=1)[0].flatten()

# Calculate accuracy
accuracy = accuracy_score(y_test, majority_vote_predictions)
print(f'Majority Voting Classifier Accuracy: {accuracy * 100:.2f}%')

# Classification report and confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, majority_vote_predictions))
print("\nClassification Report:")
print(classification_report(y_test, majority_vote_predictions))

28/28 [==============================] - 0s 2ms/step
28/28 [==============================] - 0s 5ms/step
28/28 [==============================] - 0s 7ms/step
Majority Voting Classifier Accuracy: 87.82%
Confusion Matrix:
[[464 105]
 [  3 315]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.82      0.90       569
           1       0.75      0.99      0.85       318

    accuracy                           0.88       887
   macro avg       0.87      0.90      0.87       887
weighted avg       0.91      0.88      0.88       887

In [19]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Predictions from all models
cnn_predictions = cnn_model.predict(X_test_reshaped)
rnn_predictions = rnn_model.predict(X_test_reshaped)
lstm_predictions = lstm_model.predict(X_test_reshaped)

# Convert probabilities to class labels
cnn_classes = np.argmax(cnn_predictions, axis=1)
rnn_classes = np.argmax(rnn_predictions, axis=1)
lstm_classes = np.argmax(lstm_predictions, axis=1)

# Perform majority voting
all_predictions = np.vstack((cnn_classes, rnn_classes, lstm_classes)).T
majority_vote_predictions = mode(all_predictions, axis=1)[0].flatten()

# True labels for comparison
true_labels = y_test

# Function to calculate and print evaluation metrics
def print_metrics(predictions, model_name):
    print(f"Metrics for {model_name}:")
    print(f"Precision: {precision_score(true_labels, predictions, average='binary'):.4f}")
    print(f"Recall: {recall_score(true_labels, predictions, average='binary'):.4f}")
    print(f"F1-Score: {f1_score(true_labels, predictions, average='binary'):.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(true_labels, predictions))
    print("\n")

# Evaluate each model
print_metrics(cnn_classes, "CNN")
print_metrics(rnn_classes, "RNN")
print_metrics(lstm_classes, "LSTM")
print_metrics(majority_vote_predictions, "Majority Voting Ensemble")

28/28 [==============================] - 0s 2ms/step
28/28 [==============================] - 0s 5ms/step
28/28 [==============================] - 0s 7ms/step
Metrics for CNN:
Precision: 0.5827
Recall: 0.9969
F1-Score: 0.7355
Confusion Matrix:
[[342 227]
 [  1 317]]


Metrics for RNN:
Precision: 0.1129
Recall: 0.1132
F1-Score: 0.1130
Confusion Matrix:
[[286 283]
 [282  36]]


Metrics for LSTM:
Precision: 0.9292
Recall: 0.9906
F1-Score: 0.9589
Confusion Matrix:
[[545  24]
 [  3 315]]


Metrics for Majority Voting Ensemble:
Precision: 0.7500
Recall: 0.9906
F1-Score: 0.8537
Confusion Matrix:
[[464 105]
 [  3 315]]